"""Import the platform face from the font builder's JSON export."""
import json
from pathlib import Path
import subprocess
import sys

source, output = map(Path, sys.argv[1:])
face = next(f for f in json.loads(source.read_text())["fonts"] if f["name"] == "Large Platform Number")
glyphs = face["glyphs"]
# The export includes one blank row above every glyph. Face coordinates start
# at the cap top, so remove only that shared row (including for lowercase).
assert all(g["height"] == 14 and len(g["rows"]) == 14 and set(g["rows"][0]) == {"0"} for g in glyphs.values())
lines = ['// Code generated by scripts/import-platform-font.py from tools/font.json; DO NOT EDIT.',
         'package font', '',
         '// InfotecPlatform contains the font builder platform glyphs, with their shared blank top row removed.',
         'var InfotecPlatform = newInfotecPlatform()', '',
         'func newInfotecPlatform() *Face {',
         'f := &Face{Height: 13, Baseline: 13, Spacing: 2, Glyphs: map[rune]Glyph{}, Fallback: InfotecLarge.Fallback}',
         '// Retain the existing fallback lettering for characters absent from the export.',
         'for r, g := range InfotecLarge.Glyphs { f.Glyphs[r] = g }']
for char, glyph in sorted(glyphs.items()):
    assert len(char) == 1 and 0 < glyph['width'] <= 16
    assert all(len(row) == glyph['width'] and set(row) <= {'0', '1'} for row in glyph['rows'])
    rows = ', '.join('0b' + row[::-1] for row in glyph['rows'][1:])
    lines.append("f.Glyphs[%r] = Glyph{Width: %d, Rows: []uint16{%s}}" % (char, glyph["width"], rows))
lines += ['return f', '}']
output.write_text('\n'.join(lines) + '\n')
subprocess.run(['gofmt', '-w', str(output)], check=True)
