"""Import the compact service-row face from the font builder export."""
import json
from pathlib import Path
import subprocess
import sys

source, output = map(Path, sys.argv[1:3])
name, ident, height, baseline = (sys.argv[3], sys.argv[4], int(sys.argv[5]), int(sys.argv[6])) if len(sys.argv) > 3 else ("Small main row", "InfotecSmall", 10, 8)
face = next(f for f in json.loads(source.read_text())["fonts"] if f["name"] == name)
lines = ['// Code generated by scripts/import-compact-font.py from tools/font.json; DO NOT EDIT.',
         'package font', '', f'var {ident} = &Face{{Height: {height}, Baseline: {baseline}, Spacing: 1, Glyphs: map[rune]Glyph{{']
for char, glyph in sorted(face['glyphs'].items()):
    assert len(char) == 1 and glyph['height'] == height and len(glyph['rows']) == height
    assert all(len(row) == glyph['width'] and set(row) <= {'0', '1'} for row in glyph['rows'])
    key = "'" + char.replace('\\', '\\\\').replace("'", "\\'") + "'"
    rows = ', '.join('0b' + row[::-1] for row in glyph['rows'])
    lines.append('%s: {Width: %d, Rows: []uint16{%s}},' % (key, glyph['width'], rows))
lines += ["' ': {Width: 3, Rows: make([]uint16, %d)}," % height, '}}',
          "func init() { %s.Fallback = %s.Glyphs['?'] }" % (ident, ident)]
output.write_text('\n'.join(lines) + '\n')
subprocess.run(['gofmt', '-w', str(output)], check=True)
