"""Import both clock faces without changing the font builder's pixels."""
import json
from pathlib import Path
import subprocess
import sys
source, output = map(Path, sys.argv[1:])
fonts = json.loads(source.read_text())["fonts"]
lines = ['// Code generated by scripts/import-clock-fonts.py from tools/font.json; DO NOT EDIT.', 'package font']
for name, ident in [('Clock', 'InfotecClock'), ('Small Clock', 'InfotecSmallClock')]:
    glyphs = next(f['glyphs'] for f in fonts if f['name'] == name)
    height = glyphs['0']['height']
    lines.append('var %s = &Face{Height: %d, Baseline: %d, Spacing: 1, Glyphs: map[rune]Glyph{' % (ident, height, height))
    for char, glyph in sorted(glyphs.items()):
        assert char in '0123456789:' and len(glyph['rows']) == height
        assert all(len(row) == glyph['width'] and set(row) <= {'0', '1'} for row in glyph['rows'])
        rows = ', '.join('0b' + row[::-1] for row in glyph['rows'])
        lines.append("'%s': {Width: %d, Rows: []uint16{%s}}," % (char, glyph['width'], rows))
    lines.append('}}')
output.write_text('\n'.join(lines) + '\n')
subprocess.run(['gofmt', '-w', str(output)], check=True)
