"""Import the compact service-row face from the font builder export."""
import json
from pathlib import Path
import subprocess
import sys

source, output = map(Path, sys.argv[1:])
face = next(f for f in json.loads(source.read_text())["fonts"] if f["name"] == "Small main row")
lines = ['// Code generated by scripts/import-compact-font.py from tools/font.json; DO NOT EDIT.',
         'package font', '', 'var InfotecSmall = &Face{Height: 10, Baseline: 8, Spacing: 1, Glyphs: map[rune]Glyph{']
for char, glyph in sorted(face['glyphs'].items()):
    assert len(char) == 1 and glyph['height'] == 10 and len(glyph['rows']) == 10
    assert all(len(row) == glyph['width'] and set(row) <= {'0', '1'} for row in glyph['rows'])
    key = "'" + char.replace('\\', '\\\\').replace("'", "\\'") + "'"
    rows = ', '.join('0b' + row[::-1] for row in glyph['rows'])
    lines.append('%s: {Width: %d, Rows: []uint16{%s}},' % (key, glyph['width'], rows))
lines += ['\' \': {Width: 3, Rows: make([]uint16, 10)},', '}}',
          "func init() { InfotecSmall.Fallback = InfotecSmall.Glyphs['?'] }"]
output.write_text('\n'.join(lines) + '\n')
subprocess.run(['gofmt', '-w', str(output)], check=True)
