package main

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"strings"
)

type faceSpec struct {
	varName string
	doc     string
	// file is the WOFF file name under the fonts directory.
	file string
	// keep lists the runes to emit; empty keeps every glyph in the font.
	keep string
	face *dotFace
}

func emitSource(faces []faceSpec) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/fontgen; DO NOT EDIT.\n\n")
	b.WriteString("package font\n\n")
	b.WriteString("// Row literals are binary with bit 0 on the right, so each row reads as the mirror image of the dots.\n\n")
	for _, s := range faces {
		writeFace(&b, s)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated source does not parse: %w\n%s", err, b.Bytes())
	}
	return src, nil
}

func writeFace(b *bytes.Buffer, s faceSpec) {
	f := s.face
	fmt.Fprintf(b, "// %s is %s (%q):\n// %d rows above the baseline, %d below, and %d dot of spacing between glyphs.\n",
		s.varName, s.doc, f.family, f.baseline, f.height-f.baseline, f.spacing)
	fmt.Fprintf(b, "var %s = &Face{\n", s.varName)
	fmt.Fprintf(b, "\tHeight: %d,\n", f.height)
	fmt.Fprintf(b, "\tBaseline: %d,\n", f.baseline)
	fmt.Fprintf(b, "\tSpacing: %d,\n", f.spacing)
	b.WriteString("\tGlyphs: map[rune]Glyph{\n")
	runes := make([]rune, 0, len(f.glyphs))
	for r := range f.glyphs {
		runes = append(runes, r)
	}
	slices.Sort(runes)
	for _, r := range runes {
		fmt.Fprintf(b, "\t\t%s: %s,\n", runeLiteral(r), glyphLiteral(f.glyphs[r], f.height))
	}
	b.WriteString("\t},\n")
	fmt.Fprintf(b, "\tFallback: Glyph%s,\n", glyphLiteral(f.fallback, f.height))
	b.WriteString("}\n\n")
}

func runeLiteral(r rune) string {
	if r > 0x7E {
		return fmt.Sprintf("'\\u%04X'", r)
	}
	return fmt.Sprintf("%q", r)
}

func glyphLiteral(g dotGlyph, height int) string {
	rows := make([]string, 0, height)
	for _, row := range g.rows {
		rows = append(rows, fmt.Sprintf("0b%0*b", max(g.width, 1), row))
	}
	return fmt.Sprintf("{Width: %d, Rows: []uint16{%s}}", g.width, strings.Join(rows, ", "))
}
