// Command zoneinfo extracts the browser's one time zone from the Go toolchain.
package main

import (
	"archive/zip"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	zones, err := zip.OpenReader(filepath.Join(runtime.GOROOT(), "lib", "time", "zoneinfo.zip"))
	if err != nil {
		return err
	}
	defer zones.Close()
	data, err := fs.ReadFile(zones, "Europe/London")
	if err != nil {
		return err
	}
	source := "// Code generated by go generate; DO NOT EDIT.\n" +
		"// Europe/London from the Go toolchain's IANA time zone database (public domain).\n\n" +
		"package london\n\nconst zoneData = " + strconv.QuoteToASCII(string(data)) + "\n"
	return os.WriteFile("data_gen.go", []byte(source), 0644)
}
