/**
 * Map of CRS codes to abbreviated station names.
 *
 * Many of these will never appear on the boards, but I might as well add them in anyway.
 *
 * The list below is made up of every station from [my Darwin API](https://national-rail-api.davwheat.dev/crs/) which has a name over 21 chars.
 */
const AbbreviatedStations: Record<string, string> = {
  // Max 21 chars:
  //    |<----------------->|
  ADL: 'Adlington',
  ASC: 'Ashchurch',
  AVP: 'Aylesbury V Pkwy',
  BDQ: 'Bradford Forster Sq',
  BFQ: 'Belfast Donegall Q',
  BGR: 'Boat of Garten PO',
  BHA: 'Bournemouth Hurn Apt',
  BHI: 'Birmingham Intl',
  BHM: 'Birmingham New St',
  BLE: 'Bramley',
  BLN: 'Blundellsands&Crosby',
  BMO: 'Birmingham Moor St',
  BNR: 'Brockley Whins',
  BPB: 'Blackpool Pl Beach',
  BPL: 'Barlaston Orchard Pl',
  BRG: 'Borough Gn & Wrotham',
  BRI: 'Bristol T Meads',
  BSW: 'Birmingham S Hill',
  BYK: 'Bentley',
  BYM: 'Burnley Manc Rd',
  CAZ: 'Catterick Garrison',
  CBZ: 'Corby George St (Bus)',
  CCB: 'Cardiff Ctrl Bus Stn',
  CGT: 'Cattering Garr Tesco',
  CHC: 'Charing Cross',
  CHZ: 'Chatsworth House',
  CIN: 'Cricket Inn Road',
  CIR: 'Caledonian Rd & Barn',
  CPG: 'Chipping Norton W St',
  CPY: 'Clapham',
  CSD: "Cobham & Stoke d'A",
  CSW: "Chestfld & Sw'cliffe",
  CTB: 'Castlebay Barra',
  CTW: "Church & O'twistle",
  CWX: 'Canary Wharf',
  DBG: 'Mottisfont&Dunbridge',
  DEB: 'Dereham Market Place',
  DFL: 'Dunfermline Queen Mgt',
  DOZ: 'Doncaster Nth Bus Stn',
  EAS: 'Earlston (Bus)',
  EBD: 'Ebbsfleet Intl',
  EBL: 'East Boldon',
  ECP: 'Energlyn & Churchill',
  EDA: 'Edinburgh Airport',
  EMA: 'East Midlands Airpt',
  EWD: 'Earlswood',
  FEG: 'Fellgate',
  FIZ: 'Fitzalan Square',
  FKH: 'Folkestone Harbour',
  FNY: 'Finchley Rd & Frognal',
  FSB: 'Fishbourne',
  FST: 'London Fenchurch St',
  GLT: 'Glenrothes w Thornton',
  GNH: 'Greenhithe',
  GSN: 'Garston',
  HAF: 'Heathrow T4',
  HAV: 'Heathrow T5',
  HCR: 'Hykeham Crossroads',
  HDM: 'Haddenham & T Pkwy',
  HSE: 'Hursley Post Office',
  HTR: 'Heathrow Central Bus',
  HWA: 'Heathrow T2 Bus',
  HWE: 'Heathrow T3 Bus',
  HWF: 'Heathrow T4 Bus',
  HWO: 'Heathrow T1 Bus',
  HWX: 'Heathrow T5 Bus',
  HXX: 'Heathrow T123',
  KLB: 'Kings Lynn Bus Stn',
  LAG: 'Langwith-Whaley Th',
  LCB: 'Lochboisdale (Bus)',
  LCH: 'Lochmaddy (Bus)',
  LET: 'Letchworth Gdn Cty',
  LHE: 'Loch Eil Outw Bound',
  LPY: 'Liverpool S Parkway',
  LRB: 'London Road',
  LRD: 'London Road',
  LST: 'London Liverpool St',
  LTV: 'Lichfield T V',
  LVS: 'Liverpool Landing Stg',
  LZZ: 'Leeds Whitehall (Bus)',
  MAN: 'Manchester Picc',
  MCO: 'Manchester Oxford Rd',
  MIF: 'Millfield',
  MLB: 'Millbrook',
  MLH: 'Mill Hill',
  NCZ: 'Newcastle Ctrl Metro',
  NWE: 'Newport (Essex)',
  NWP: 'Newport (Gwent)',
  OUD: 'Oundle Mkt Pl (Bus)',
  OXN: 'Oxenholme',
  PAD: 'London Padd',
  PBU: 'Peterborough (Bus)',
  PDK: 'Pembroke Dock',
  PIZ: 'Pickering Eastgate',
  PMG: 'Porthmadog Harbour',
  PMH: 'Portsmouth Hbr',
  PMS: 'Portsmouth & SSea',
  PPK: 'Possilpark/Parkhouse',
  PRA: 'Prestwick Intl Airpt',
  PWC: 'Prestwich Metrolink',
  PYG: 'Paisley Gilmour St',
  QRB: "Queenstown Rd B'sea",
  RAV: 'Ravenglass',
  RCF: 'Radcliffe Metrolink',
  RDF: 'Radcliffe',
  RGL: 'Rugeley T V',
  RGW: 'Ramsgreave & Wilpsh',
  RHA: 'Robin Hood Airport',
  RIA: 'Rhoose Cardiff Airpt',
  RMG: 'Ramsgate Harbour',
  RMK: 'Richmond Nth Yorks',
  SAI: 'Sheffield Arena',
  SBV: 'St Budeaux Vic Rd',
  SCN: 'Stone, Crown Street',
  SDC: 'Shoreditch High St',
  SFA: 'Stratford Intl',
  SGB: 'Smethwick G Bridge',
  SGH: 'South Gosforth',
  SGQ: 'Stone Granville Sq',
  SHQ: 'Sheffield Cathedral',
  SHV: 'Southsea Hoverport',
  SHZ: 'South Hylton',
  SJN: 'St James',
  SKN: 'St Keyne W Well Halt',
  SLQ: 'St Leonards WS',
  SMR: 'Smethwick Rolfe St',
  SMT: 'St Margarets',
  SOA: 'Southampton Airpt Pwy',
  SOU: 'Southampton Ctl',
  SOY: 'Stornoway, Lewis',
  SOZ: 'Southport, Lord St',
  SRB: 'Stirling Bus Stn',
  SRF: 'Stretford Metrolink',
  STI: 'Stadium of Light',
  STJ: 'Severn Tunnel Jn',
  STP: 'Lon St Pancras Intl',
  STQ: 'Southampton Town Q',
  STZ: 'St Peters',
  SWB: 'Swaffham Tourist Ctr',
  SWC: 'Swinderby A46 Rbt',
  SWH: 'Shaftesbury Town Hl',
  SWN: 'Swinton',
  SWP: 'Stranraer West Pier',
  TBR: 'Tilbury Riverside',
  TIN: 'Tinsley Meadowhall',
  TVA: 'Tees Valley Airpt',
  TYP: 'Tynemouth',
  UNV: 'University T&W',
  VAE: 'Valley Centertainment',
  WBE: 'Wadebridge Bus Stn',
  WCH: 'Whitchurch',
  WDY: 'Woodley, Hunters Inn',
  WEN: 'Wells-Next-The-Sea',
  WER: 'Wedgwood Old Rd Br',
  WHH: 'Whitehill (Bus)',
  WHP: 'West Hampstead TL',
  WHT: 'Whitchurch',
  WIS: 'Wisbech Horsefair',
  WLN: 'Wellington',
  WMP: 'Witney Market Place',
  WMW: 'Walthamstow Q Road',
  WNC: 'Windsor & Eton',
  WNR: 'Windsor & Eton',
  WOF: 'Worcester Fgt St',
  WOP: 'Worcestershire Pkwy',
  WOX: 'Workington Bus Stn',
  WSM: 'Weston S Mare',
  WTC: 'Whitchurch',
  WWC: 'Woolwich',
  XBO: 'Melksham Market Pl',
  XBV: 'Minehead Butlins',
  XCF: 'Cardiff Intl Airpt',
  XDJ: 'Plymouth Saltash Rd',
  XDM: 'Chippenham Bath Rd',
  XDN: 'Chippenham New Rd',
  XDU: 'Bristol Temple Gate',
  XEK: 'Moretonhampstead',
  XET: 'Nutfield Mem Hall',
  XFG: 'Birmingham Airpt',
  XGO: 'Catterick Camp Ctr',
  XLB: 'Leeds Brad Airpt',
  XPB: 'Bristol Intl Airpt',
  XSK: 'Southampton W Docks',
  XSN: 'Southampton E Docks',
  XTH: 'Stansted Airpt Bus',
  XTV: 'Rhymney Tredegar',
  XWU: 'Warwick University',
  XWX: 'Wallingford Mkt Pl',
  YMH: 'Yarmouth',
  ZBC: 'Barons Court LU',
  ZBS: 'Baker Street LU',
  ZCK: 'Cockfosters LU',
  ZDE: 'Dagenham East LU',
  ZEL: 'Elephant & Castle LU',
  ZET: "Earl's Court LU",
  ZHA: 'Hammersmith LU',
  ZHS: 'Kensington H St LU',
  ZNP: 'Newbury Park LU',
  ZPC: 'Piccadilly Circus LU',
  ZTH: 'Tower Hill LU',
  ZTU: 'Turnham Green LU',
};

export function getStationWithOverride(crs: string, name: string): string {
  return AbbreviatedStations[crs] ?? name;
}
