// Package london supplies the browser's time zone without embedding every zone.
package london

import "time"

// Regenerated by the web build so time zone updates follow the Go toolchain.
//go:generate go run ../../cmd/zoneinfo

func Load() (*time.Location, error) {
	return time.LoadLocationFromTZData("Europe/London", []byte(zoneData))
}
