[Unit]
After=departure-board-manager.service
Wants=departure-board-manager.service
RequiresMountsFor=/boot/firmware/departure-board.toml

[Service]
ExecStart=
ExecStart=/opt/departure-board/board -config /boot/firmware/departure-board.toml -setup-status /run/departure-board/network.json
